sources:
    - name: dbt_practice_dataset
      description: This is a practice dataset from dbt training
      database: dbt-project-486613
      schema: dbt_practice_dataset
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.